apiVersion: v1
kind: Service
metadata:
  name: kafka-hs
  labels:
    app: k8s-playground
    tier: mq
    name: kafka
spec:
  ports:
  - port: 9093
    name: server
  clusterIP: None
  selector:
    app: k8s-playground
    tier: mq
    name: kafka