kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  k8s-playground-cassandra-local-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi 
  storageClassName: local-storage