apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-playground-cassandra-local-pv
spec:
  capacity:
    storage: 0.5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/playground/cassandra
  nodeAffinity: # nodeAffinity is a required field for local PersistentVolumes
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - my-node