apiVersion: v1
kind: Service
metadata:
  name: k8s-playground-cassandra-service # DNS name
  labels:
    app: k8s-playground
    tier: database
    name: cassandra
spec:
  type: LoadBalancer
  selector:
    app: k8s-playground
    tier: database
    name: cassandra
  ports:
    - port: 9042
    