apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-playground-web-deployment
  labels:
    app: k8s-playground
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-playground
      tier: web
  template:
    metadata:
      labels:
        app: k8s-playground
        tier: web
    spec:
      containers:
      - name: k8s-playground-web
        image: bharathkumarravichandran/k8s-playground-web:1.0.0
        resources:
          requests:
            cpu: "50m" # 50milliCPU / 0.05vCPU/Core
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - containerPort: 3000
          name: http
