apiVersion: v1
kind: Service
metadata:
  name: k8s-playground-web-service # DNS name
spec:
  type: LoadBalancer
  selector:
    app: k8s-playground
    tier: web
  ports:
    - protocol: TCP
      port: 3041 # service listens to this port
      targetPort: 3000 # service forwards requests to this port
